spring.application.name=printshop


spring.datasource.url=jdbc:h2:mem:printshop_db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

app.upload.pdf-dir=./uploads/pdfs
app.upload.cover-dir=./uploads/covers

server.port=8080

# ==================================================================
# إعدادات PostgreSQL (هنرجعلها لما نخلص تجربة H2 ونجهز نستخدم داتابيز حقيقية)
# لو عايز ترجع لها: احذف إعدادات H2 فوق، وشيل # من السطور دي
# ==================================================================
# spring.datasource.url=jdbc:postgresql://localhost:5432/printshop_db
# spring.datasource.username=postgres
# spring.datasource.password=changeme
# spring.datasource.driver-class-name=org.postgresql.Driver
